<?php

namespace DoctrineORMModule\Proxy\__CG__\TenilBoleto\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BoletoRetorno extends \TenilBoleto\Entity\BoletoRetorno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'idBoleto', 'registro', 'tipoInscrEmpresa', 'numInscrEmpresa', 'idEmpresaBanco', 'numControlePart', 'nossoNumero', 'nossoNumeroDv', 'idRateioCredito', 'carteira', 'idOcorrencia', 'dataPagamento', 'numDocumento', 'dataVencimento', 'valorTitulo', 'codBanco', 'agencia', 'despCobranca', 'outrasDespesas', 'jurosAtraso', 'iof', 'descontoConcedido', 'valorRecebido', 'jurosMora', 'outrosRecebimentos', 'motivoCodOcorrencia', 'numCartorio', 'numProtocolo', 'valorAbatimento', 'abatimentoNaoAprov', 'valorPagamento', 'indicativoDc', 'indicadorValor', 'valorAjuste', 'sequencial', 'updatedAt', 'createdAt');
        }

        return array('__isInitialized__', 'id', 'idBoleto', 'registro', 'tipoInscrEmpresa', 'numInscrEmpresa', 'idEmpresaBanco', 'numControlePart', 'nossoNumero', 'nossoNumeroDv', 'idRateioCredito', 'carteira', 'idOcorrencia', 'dataPagamento', 'numDocumento', 'dataVencimento', 'valorTitulo', 'codBanco', 'agencia', 'despCobranca', 'outrasDespesas', 'jurosAtraso', 'iof', 'descontoConcedido', 'valorRecebido', 'jurosMora', 'outrosRecebimentos', 'motivoCodOcorrencia', 'numCartorio', 'numProtocolo', 'valorAbatimento', 'abatimentoNaoAprov', 'valorPagamento', 'indicativoDc', 'indicadorValor', 'valorAjuste', 'sequencial', 'updatedAt', 'createdAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BoletoRetorno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdBoleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBoleto', array());

        return parent::getIdBoleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBoleto($idBoleto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBoleto', array($idBoleto));

        return parent::setIdBoleto($idBoleto);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistro', array());

        return parent::getRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistro($registro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistro', array($registro));

        return parent::setRegistro($registro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoInscrEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoInscrEmpresa', array());

        return parent::getTipoInscrEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoInscrEmpresa($tipoInscrEmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoInscrEmpresa', array($tipoInscrEmpresa));

        return parent::setTipoInscrEmpresa($tipoInscrEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumInscrEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumInscrEmpresa', array());

        return parent::getNumInscrEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumInscrEmpresa($numInscrEmpresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumInscrEmpresa', array($numInscrEmpresa));

        return parent::setNumInscrEmpresa($numInscrEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmpresaBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmpresaBanco', array());

        return parent::getIdEmpresaBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmpresaBanco($idEmpresaBanco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmpresaBanco', array($idEmpresaBanco));

        return parent::setIdEmpresaBanco($idEmpresaBanco);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumControlePart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumControlePart', array());

        return parent::getNumControlePart();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumControlePart($numControlePart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumControlePart', array($numControlePart));

        return parent::setNumControlePart($numControlePart);
    }

    /**
     * {@inheritDoc}
     */
    public function getNossoNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNossoNumero', array());

        return parent::getNossoNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNossoNumero($nossoNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNossoNumero', array($nossoNumero));

        return parent::setNossoNumero($nossoNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getNossoNumeroDv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNossoNumeroDv', array());

        return parent::getNossoNumeroDv();
    }

    /**
     * {@inheritDoc}
     */
    public function setNossoNumeroDv($nossoNumeroDv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNossoNumeroDv', array($nossoNumeroDv));

        return parent::setNossoNumeroDv($nossoNumeroDv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRateioCredito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRateioCredito', array());

        return parent::getIdRateioCredito();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRateioCredito($idRateioCredito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRateioCredito', array($idRateioCredito));

        return parent::setIdRateioCredito($idRateioCredito);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarteira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarteira', array());

        return parent::getCarteira();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarteira($carteira)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarteira', array($carteira));

        return parent::setCarteira($carteira);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdOcorrencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdOcorrencia', array());

        return parent::getIdOcorrencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdOcorrencia($idOcorrencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdOcorrencia', array($idOcorrencia));

        return parent::setIdOcorrencia($idOcorrencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataPagamento', array());

        return parent::getDataPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataPagamento($dataPagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataPagamento', array($dataPagamento));

        return parent::setDataPagamento($dataPagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumDocumento', array());

        return parent::getNumDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumDocumento($numDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumDocumento', array($numDocumento));

        return parent::setNumDocumento($numDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataVencimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataVencimento', array());

        return parent::getDataVencimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataVencimento($dataVencimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataVencimento', array($dataVencimento));

        return parent::setDataVencimento($dataVencimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTitulo', array());

        return parent::getValorTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTitulo($valorTitulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTitulo', array($valorTitulo));

        return parent::setValorTitulo($valorTitulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodBanco', array());

        return parent::getCodBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodBanco($codBanco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodBanco', array($codBanco));

        return parent::setCodBanco($codBanco);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencia', array());

        return parent::getAgencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencia($agencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencia', array($agencia));

        return parent::setAgencia($agencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDespCobranca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDespCobranca', array());

        return parent::getDespCobranca();
    }

    /**
     * {@inheritDoc}
     */
    public function setDespCobranca($despCobranca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDespCobranca', array($despCobranca));

        return parent::setDespCobranca($despCobranca);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutrasDespesas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutrasDespesas', array());

        return parent::getOutrasDespesas();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutrasDespesas($outrasDespesas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutrasDespesas', array($outrasDespesas));

        return parent::setOutrasDespesas($outrasDespesas);
    }

    /**
     * {@inheritDoc}
     */
    public function getJurosAtraso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJurosAtraso', array());

        return parent::getJurosAtraso();
    }

    /**
     * {@inheritDoc}
     */
    public function setJurosAtraso($jurosAtraso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJurosAtraso', array($jurosAtraso));

        return parent::setJurosAtraso($jurosAtraso);
    }

    /**
     * {@inheritDoc}
     */
    public function getIof()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIof', array());

        return parent::getIof();
    }

    /**
     * {@inheritDoc}
     */
    public function setIof($iof)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIof', array($iof));

        return parent::setIof($iof);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescontoConcedido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescontoConcedido', array());

        return parent::getDescontoConcedido();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescontoConcedido($descontoConcedido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescontoConcedido', array($descontoConcedido));

        return parent::setDescontoConcedido($descontoConcedido);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorRecebido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorRecebido', array());

        return parent::getValorRecebido();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorRecebido($valorRecebido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorRecebido', array($valorRecebido));

        return parent::setValorRecebido($valorRecebido);
    }

    /**
     * {@inheritDoc}
     */
    public function getJurosMora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJurosMora', array());

        return parent::getJurosMora();
    }

    /**
     * {@inheritDoc}
     */
    public function setJurosMora($jurosMora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJurosMora', array($jurosMora));

        return parent::setJurosMora($jurosMora);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutrosRecebimentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutrosRecebimentos', array());

        return parent::getOutrosRecebimentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutrosRecebimentos($outrosRecebimentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutrosRecebimentos', array($outrosRecebimentos));

        return parent::setOutrosRecebimentos($outrosRecebimentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivoCodOcorrencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivoCodOcorrencia', array());

        return parent::getMotivoCodOcorrencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivoCodOcorrencia($motivoCodOcorrencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivoCodOcorrencia', array($motivoCodOcorrencia));

        return parent::setMotivoCodOcorrencia($motivoCodOcorrencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumCartorio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumCartorio', array());

        return parent::getNumCartorio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumCartorio($numCartorio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumCartorio', array($numCartorio));

        return parent::setNumCartorio($numCartorio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumProtocolo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumProtocolo', array());

        return parent::getNumProtocolo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumProtocolo($numProtocolo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumProtocolo', array($numProtocolo));

        return parent::setNumProtocolo($numProtocolo);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorAbatimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorAbatimento', array());

        return parent::getValorAbatimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorAbatimento($valorAbatimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorAbatimento', array($valorAbatimento));

        return parent::setValorAbatimento($valorAbatimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbatimentoNaoAprov()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbatimentoNaoAprov', array());

        return parent::getAbatimentoNaoAprov();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbatimentoNaoAprov($abatimentoNaoAprov)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbatimentoNaoAprov', array($abatimentoNaoAprov));

        return parent::setAbatimentoNaoAprov($abatimentoNaoAprov);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorPagamento', array());

        return parent::getValorPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorPagamento($valorPagamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorPagamento', array($valorPagamento));

        return parent::setValorPagamento($valorPagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicativoDc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicativoDc', array());

        return parent::getIndicativoDc();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndicativoDc($indicativoDc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndicativoDc', array($indicativoDc));

        return parent::setIndicativoDc($indicativoDc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndicadorValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndicadorValor', array());

        return parent::getIndicadorValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndicadorValor($indicadorValor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndicadorValor', array($indicadorValor));

        return parent::setIndicadorValor($indicadorValor);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorAjuste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorAjuste', array());

        return parent::getValorAjuste();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorAjuste($valorAjuste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorAjuste', array($valorAjuste));

        return parent::setValorAjuste($valorAjuste);
    }

    /**
     * {@inheritDoc}
     */
    public function getSequencial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSequencial', array());

        return parent::getSequencial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSequencial($sequencial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSequencial', array($sequencial));

        return parent::setSequencial($sequencial);
    }

}
