<?php

namespace DoctrineORMModule\Proxy\__CG__\TenilEvento\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \TenilEvento\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'inscricoes', 'imagens', 'nome', 'tema', 'descricao', 'dataInicio', 'dataFim', 'horaInicio', 'horaFim', 'qtdVagas', 'flagInscricoesAbertas', 'organizador', 'email', 'slug', 'valorInscricao', 'flagEventoGratuito', 'updatedAt', 'createdAt');
        }

        return array('__isInitialized__', 'id', 'inscricoes', 'imagens', 'nome', 'tema', 'descricao', 'dataInicio', 'dataFim', 'horaInicio', 'horaFim', 'qtdVagas', 'flagInscricoesAbertas', 'organizador', 'email', 'slug', 'valorInscricao', 'flagEventoGratuito', 'updatedAt', 'createdAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setTema($tema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTema', array($tema));

        return parent::setTema($tema);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio($dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', array($dataInicio));

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim($dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', array($dataFim));

        return parent::setDataFim($dataFim);
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraInicio($horaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraInicio', array($horaInicio));

        return parent::setHoraInicio($horaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraFim($horaFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraFim', array($horaFim));

        return parent::setHoraFim($horaFim);
    }

    /**
     * {@inheritDoc}
     */
    public function setQtdVagas($qtdVagas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtdVagas', array($qtdVagas));

        return parent::setQtdVagas($qtdVagas);
    }

    /**
     * {@inheritDoc}
     */
    public function setFlagInscricoesAbertas($flagInscricoesAbertas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlagInscricoesAbertas', array($flagInscricoesAbertas));

        return parent::setFlagInscricoesAbertas($flagInscricoesAbertas);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizador($organizador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizador', array($organizador));

        return parent::setOrganizador($organizador);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setValorInscricao($valorInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorInscricao', array($valorInscricao));

        return parent::setValorInscricao($valorInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function setFlagEventoGratuito($flagEventoGratuito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlagEventoGratuito', array($flagEventoGratuito));

        return parent::setFlagEventoGratuito($flagEventoGratuito);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getTema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTema', array());

        return parent::getTema();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', array());

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', array());

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraInicio', array());

        return parent::getHoraInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraFim', array());

        return parent::getHoraFim();
    }

    /**
     * {@inheritDoc}
     */
    public function getQtdVagas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtdVagas', array());

        return parent::getQtdVagas();
    }

    /**
     * {@inheritDoc}
     */
    public function isFlagInscricoesAbertas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFlagInscricoesAbertas', array());

        return parent::isFlagInscricoesAbertas();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizador', array());

        return parent::getOrganizador();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getValorInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorInscricao', array());

        return parent::getValorInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function isFlagEventoGratuito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFlagEventoGratuito', array());

        return parent::isFlagEventoGratuito();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array());

        return parent::setSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagens', array());

        return parent::getImagens();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagens($imagens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagens', array($imagens));

        return parent::setImagens($imagens);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscricoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscricoes', array());

        return parent::getInscricoes();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscricoes($inscricoes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscricoes', array($inscricoes));

        return parent::setInscricoes($inscricoes);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array());

        return parent::setUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

}
