<?php

namespace DoctrineORMModule\Proxy\__CG__\TenilUser\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Perfil extends \TenilUser\Entity\Perfil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'user', 'id', 'nome', 'sobrenome', 'tratamento', 'isGravatar', 'foto', 'fone1numero', 'fone1ddd', 'fone1tipo', 'fone1ramal', 'fone1contato', 'fone2numero', 'fone2ddd', 'fone2tipo', 'fone2ramal', 'fone2contato', 'fone3numero', 'fone3ddd', 'fone3tipo', 'fone3ramal', 'fone3contato', 'logradouro', 'numero', 'complemento', 'bairro', 'localidade', 'uf', 'cep');
        }

        return array('__isInitialized__', 'user', 'id', 'nome', 'sobrenome', 'tratamento', 'isGravatar', 'foto', 'fone1numero', 'fone1ddd', 'fone1tipo', 'fone1ramal', 'fone1contato', 'fone2numero', 'fone2ddd', 'fone2tipo', 'fone2ramal', 'fone2contato', 'fone3numero', 'fone3ddd', 'fone3tipo', 'fone3ramal', 'fone3contato', 'logradouro', 'numero', 'complemento', 'bairro', 'localidade', 'uf', 'cep');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Perfil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\TenilUser\Entity\Perfil $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getSobrenome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSobrenome', array());

        return parent::getSobrenome();
    }

    /**
     * {@inheritDoc}
     */
    public function getTratamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTratamento', array());

        return parent::getTratamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsGravatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsGravatar', array());

        return parent::getIsGravatar();
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone1numero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone1numero', array());

        return parent::getFone1numero();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone1ddd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone1ddd', array());

        return parent::getFone1ddd();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone1tipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone1tipo', array());

        return parent::getFone1tipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone1ramal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone1ramal', array());

        return parent::getFone1ramal();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone1contato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone1contato', array());

        return parent::getFone1contato();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone2numero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone2numero', array());

        return parent::getFone2numero();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone2ddd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone2ddd', array());

        return parent::getFone2ddd();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone2tipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone2tipo', array());

        return parent::getFone2tipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone2ramal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone2ramal', array());

        return parent::getFone2ramal();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone2contato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone2contato', array());

        return parent::getFone2contato();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone3numero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone3numero', array());

        return parent::getFone3numero();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone3ddd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone3ddd', array());

        return parent::getFone3ddd();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone3tipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone3tipo', array());

        return parent::getFone3tipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone3ramal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone3ramal', array());

        return parent::getFone3ramal();
    }

    /**
     * {@inheritDoc}
     */
    public function getFone3contato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone3contato', array());

        return parent::getFone3contato();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogradouro', array());

        return parent::getLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', array());

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function getComplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComplemento', array());

        return parent::getComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', array());

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidade', array());

        return parent::getLocalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUf', array());

        return parent::getUf();
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', array());

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setSobrenome($sobrenome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSobrenome', array($sobrenome));

        return parent::setSobrenome($sobrenome);
    }

    /**
     * {@inheritDoc}
     */
    public function setTratamento($tratamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTratamento', array($tratamento));

        return parent::setTratamento($tratamento);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsGravatar($isGravatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsGravatar', array($isGravatar));

        return parent::setIsGravatar($isGravatar);
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone1numero($fone1numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone1numero', array($fone1numero));

        return parent::setFone1numero($fone1numero);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone1ddd($fone1ddd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone1ddd', array($fone1ddd));

        return parent::setFone1ddd($fone1ddd);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone1tipo($fone1tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone1tipo', array($fone1tipo));

        return parent::setFone1tipo($fone1tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone1ramal($fone1ramal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone1ramal', array($fone1ramal));

        return parent::setFone1ramal($fone1ramal);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone1contato($fone1contato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone1contato', array($fone1contato));

        return parent::setFone1contato($fone1contato);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone2numero($fone2numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone2numero', array($fone2numero));

        return parent::setFone2numero($fone2numero);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone2ddd($fone2ddd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone2ddd', array($fone2ddd));

        return parent::setFone2ddd($fone2ddd);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone2tipo($fone2tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone2tipo', array($fone2tipo));

        return parent::setFone2tipo($fone2tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone2ramal($fone2ramal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone2ramal', array($fone2ramal));

        return parent::setFone2ramal($fone2ramal);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone2contato($fone2contato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone2contato', array($fone2contato));

        return parent::setFone2contato($fone2contato);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone3numero($fone3numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone3numero', array($fone3numero));

        return parent::setFone3numero($fone3numero);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone3ddd($fone3ddd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone3ddd', array($fone3ddd));

        return parent::setFone3ddd($fone3ddd);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone3tipo($fone3tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone3tipo', array($fone3tipo));

        return parent::setFone3tipo($fone3tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone3ramal($fone3ramal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone3ramal', array($fone3ramal));

        return parent::setFone3ramal($fone3ramal);
    }

    /**
     * {@inheritDoc}
     */
    public function setFone3contato($fone3contato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone3contato', array($fone3contato));

        return parent::setFone3contato($fone3contato);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogradouro($logradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogradouro', array($logradouro));

        return parent::setLogradouro($logradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', array($numero));

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function setComplemento($complemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComplemento', array($complemento));

        return parent::setComplemento($complemento);
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', array($bairro));

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidade($localidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidade', array($localidade));

        return parent::setLocalidade($localidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setUf($uf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUf', array($uf));

        return parent::setUf($uf);
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', array($cep));

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
