<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user-auth'));

echo $this->form()->openTag($form);

echo '<div class="form-group">';
$email = $form->get('email');
echo $this->formLabel($email);
echo '<div class="col-lg-10">';
echo $this->formInput($email);
//                echo $this->formElementErrors($email);
echo '</div>';
echo '</div>';

echo '<div class="form-group">';
$password = $form->get('password');
echo $this->formLabel($password);
echo '<div class="col-lg-10">';
echo $this->formInput($password);
//                echo $this->formElementErrors($password);
echo '</div>';
echo '</div>';

echo '<div class="form-group">';
$name = $form->get('submit');
echo '<div class="col-lg-offset-2 col-lg-10">';
echo $this->formSubmit($name);
echo '</div>';
echo '</div>';

echo $this->form()->closeTag();


foreach ($form as $element) {
    echo $this->formElementErrors($element);
}
?>