<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user/default', array('controller'=> 'auth', 'action'=>'index')));

echo $this->form()->openTag($form);

$email = $form->get('email');
echo $this->formInput($email);

$password = $form->get('password');
echo $this->formInput($password);

$name = $form->get('submit');
echo $this->formSubmit($name);
?>
<div class="footer">
    <p><a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'forgot')) ?>">Esqueceu a senha?</a></p>
    <p>Não tem uma conta? <a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'register')) ?>">Cadastre-se</a></p>
</div>

<?php echo $this->form()->closeTag(); ?>