<img alt="Cloud-logo" class="logo" height="70" src="/img/cloud-logo.svg">
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user-auth'));

echo $this->form()->openTag($form);

$email = $form->get('email');
echo $this->formInput($email);

$password = $form->get('password');
echo $this->formInput($password);

$name = $form->get('submit');
echo $this->formSubmit($name);

?>
<div class="footer">
<p><a href="/forgot_password/new">Esqueceu a senha?</a></p>
<p>Não tem uma conta? <a href="<?php echo $this->url('tenil-user-register') ?>">Cadastre-se</a></p>
</div>

<?php
echo $this->form()->closeTag();

foreach ($form as $element) {
    echo $this->formElementErrors($element);
}
?>