<?php
$this->headLink()->appendStylesheet('/css/signin.css');

$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user/default', array('controller'=> 'auth', 'action'=>'login')));

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);

echo $formLabel->openTag() . $this->translate($form->getAttribute('label')) . $formLabel->closeTag();

$email = $form->get('email');
$email->setAttribute('autofocus', 'autofocus');
echo $this->formInput($email);

$password = $form->get('password');
echo $this->formInput($password);

$name = $form->get('submit');
echo $this->formSubmit($name);
?>
<div class="footer">
    <p><a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'forgot')) ?>">Esqueceu a senha?</a></p>
    <p>Não tem uma conta? <a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'register')) ?>">Cadastre-se</a></p>
</div>

<?php echo $this->form()->closeTag(); ?>