<div class="page-header">
    <h1><?php echo $this->translate('Activate') ?> <small>Ativação de conta</small></h1>
</div>
<div class="row">
    <div class="col-md-12">
        <?php if (isset($this->user)): ?>
            <div class="alert alert-success"><strong>Parabéns!</strong> Conta ativada com sucesso.</div>
        <?php else: ?>
            <div class="alert alert-danger"><strong>Erro!</strong> Chave de ativação não encontrada no sistema.</div>
        <?php endif; ?>
    </div>
</div>