<?php
$this->headLink()->appendStylesheet('/css/signin.css');

$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'forgot')));

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
echo $formLabel->openTag() . $form->getAttribute('label') . $formLabel->closeTag();

$security = $form->get('security');
echo $this->formInput($security);

$email = $form->get('email');
echo $this->formInput($email);

$submit = $form->get('submit');
echo $this->formSubmit($submit);
?>
<div class="footer">
    <p>Não tem uma conta? <a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'register')) ?>">Cadastre-se</a></p>
</div>

<?php echo $this->form()->closeTag(); ?>