<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $this->translate('Usuários') ?>
            <small><?php echo $this->translate('Administração de usuários') ?></small>
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Id</th>
            <th>Img</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Ativo</th>
            <th>Editar</th>
            <th>Excluir</th>
            <th>Data</th>
        </tr>
        <?php foreach ($this->data as $value): ?>

            <tr>
                <td><?php echo $this->escapeHtml($value->getId()); ?></td>
                <td><?php echo $this->gravatar($value->getEmail())->setImgSize(40)->getImgTag(); ?></td>
                <td><?php echo $this->escapeHtml($value->getPerfil()); ?></td>
                <td><?php echo $this->escapeHtml($value->getEmail()); ?></td>
                <td <?php echo $value->getActive() ? 'class="success"' : 'class="danger"'; ?>><?php echo $value->getActive() ? 'Sim' : 'Não'; ?></td>
                <td>
                    <a href="<?php echo $this->url('tenil-user/default', array('action' => 'edit', 'id' => $value->getId())) ?>">Editar</a>
                </td>
                <td>
                    <a href="<?php echo $this->url('tenil-user/default', array('action' => 'delete', 'id' => $value->getId()))  ?>">Excluir</a>
                </td>
                <td>
                    <small><?php
                        echo $this->dateFormat(
                            $value->getCreatedAt(), IntlDateFormatter::MEDIUM, // date
                            IntlDateFormatter::SHORT, // time
                            "pt_BR"
                        );
                        ?></small>
                    <br/>
                    <small><?php
                        echo $this->dateFormat(
                            $value->getUpdatedAt(), IntlDateFormatter::MEDIUM, // date
                            IntlDateFormatter::SHORT, // time
                            "pt_BR"
                        );
                        ?></small>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <a class="btn btn-default"
                   href="<?php echo $this->url('tenil-user/default', array('action' => 'add')); ?>"
                   target="_self">Novo</a>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <?php
        echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator/control_v2', array('route' => 'tenil-user/paginator'));
        ?>
    </div>
</div>