<?php
$title = $this->escapeHtml($this->translate('Crie sua conta'));
$this->headTitle($title);
//$this->headLink()->appendStylesheet('/css/signin.css');
?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user/default', array('action' => 'register')));
$form->setAttributes(array(
    'class' => 'col s12 m8 offset-m2 l6 offset-l3',
    'label' => 'Crie sua conta'
));
// $formLabel = $this->plugin('formLabel');
/*
$this->formElementErrors()
    ->setMessageOpenFormat('<span id="helpBlock" class="help-block">')
    ->setMessageSeparatorString('</span><span id="helpBlock" class="help-block">')
    ->setMessageCloseString('</span>');
*/
?>
<div class="section">
    <div class="container">
        <div class="row">
            <?php
            echo $this->form()->openTag($form);

            $security = $form->get('security');
            echo $this->formInput($security);
            ?>
            <div class="row">
                <div class="col s12">
                    <h4 class="light center-align"><?php echo $form->getAttribute('label'); ?></h4>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <?php
                    $email = $form->get('user')->get('email');
                    $email->setAttribute('autofocus', 'autofocus');
                    $email->setAttribute('class', 'validate');
                    echo $this->formInput($email);
                    echo $this->formLabel($email);
                    echo $this->formElementErrors($email);
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <?php
                    $nome = $form->get('user')->get('perfil')->get('nome');
                    $nome->setAttribute('class', 'validate')
                        ->setAttribute('aria-described-by', 'helpBlock')
                        ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
                    echo $this->formInput($nome);
                    echo $this->formLabel($nome);
                    echo $this->formElementErrors($nome);
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <?php
                    $password = $form->get('user')->get('password');
                    echo $this->formInput($password);
                    echo $this->formLabel($password);
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <?php
                    $submit = $form->get('submit');
                    $submit->setAttribute('class', 'waves-effect waves-light btn col s12');
                    echo $this->formSubmit($submit);
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <p>Ao me inscrever, concordo com os <a href="#!">termos de serviço</a>, <a href="#!">política de
                            privacidade</a>, <a
                            href="#!">política de
                            cookies</a> e em receber comunicações de email marketing da empresa.</p>
                    <p>Já tem uma conta? <a
                            href="<?php echo $this->url('tenil-auth', array('action' => 'login')) ?>">Faça
                            login</a></p>

                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>