<?php
// Título da página
$title = $this->translate('Inscricoes');
$this->headTitle($title);
$data = $this->data;
?>

<?php foreach ($data as $inscricao): ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $inscricao->getNome(); ?>
                <span class="pull-right"><?php echo $inscricao->getEmail(); ?></span>
            </h3>
        </div>

        <div class="panel-body">

            <dl class="dl-horizontal">
                <dt>Data início</dt>
                <dd><?php
                    echo $this->dateFormat(
                        $inscricao->getCriadoEm(),
                        IntlDateFormatter::MEDIUM, // date
                        IntlDateFormatter::NONE, // time
                        "pt_BR"
                    );
                    ?>
                </dd>
                <dt>Data encerramento</dt>
                <dd><?php
                    echo $this->dateFormat(
                        $inscricao->getModificadoEm(),
                        IntlDateFormatter::MEDIUM, // date
                        IntlDateFormatter::NONE, // time
                        "pt_BR"
                    );
                    ?></dd>
            </dl>
        </div>
        <div class="panel-footer">
            <div class="clearfix">
                <a href="<?php echo $this->url('tenil-evento/detail', array('controller' => 'evento', 'action' => 'detail', 'id' => $inscricao->getId())) ?>"
                   class="btn btn-default pull-right" data-toggle="tooltip" data-placement="left"
                   title="" data-original-title="Faça sua inscrição.">Saiba mais</a>
            </div>
        </div>
    </div>
<?php endforeach; ?>