<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $this->translate('Meus dados') ?>
        </div>
    </div>
    <?php
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action', $this->url('tenil-user/default', array('controller' => 'profile', 'action' => 'edit')));

    echo $this->form()->openTag($form);

    ?>
    <div class="panel-body">


        <?php


        $id = $form->get('id');
        echo $this->formHidden($id);

        $security = $form->get('security');
        echo $this->formElement($security);

        echo '<div class="form-group">';
        $tratamento = $form->get('tratamento');
        $sobrenome = $form->get('sobrenome');
        $nome = $form->get('nome');
        echo $this->formLabel($nome);
        echo '<div class="col-md-2">';
        echo $this->formSelect($tratamento);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formInput($nome);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formInput($sobrenome);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $fone1numero = $form->get('fone1numero');
        $fone1ddd = $form->get('fone1ddd');
        $fone1tipo = $form->get('fone1tipo');
        echo $this->formLabel($fone1numero);
        echo '<div class="col-md-2">';
        echo $this->formInput($fone1ddd);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formInput($fone1numero);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formSelect($fone1tipo);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $fone2numero = $form->get('fone2numero');
        $fone2ddd = $form->get('fone2ddd');
        $fone2tipo = $form->get('fone2tipo');
        echo $this->formLabel($fone2numero);
        echo '<div class="col-md-2">';
        echo $this->formInput($fone2ddd);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formInput($fone2numero);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formSelect($fone2tipo);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $fone3numero = $form->get('fone3numero');
        $fone3ddd = $form->get('fone3ddd');
        $fone3tipo = $form->get('fone3tipo');
        echo $this->formLabel($fone3numero);
        echo '<div class="col-md-2">';
        echo $this->formInput($fone3ddd);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formInput($fone3numero);
        echo '</div>';
        echo '<div class="col-md-4">';
        echo $this->formSelect($fone3tipo);
        echo '</div>';
        echo '</div>';


        echo '<div class="form-group">';

        $logradouro = $form->get('logradouro');
        echo $this->formLabel($logradouro);
        echo '<div class="col-md-10">';
        echo $this->formInput($logradouro);
        echo '</div>';

        $numero = $form->get('numero');
        echo '<div class="col-md-offset-2 col-md-2">';
        echo $this->formInput($numero);
        echo '</div>';

        $complemento = $form->get('complemento');
        echo '<div class="col-md-4">';
        echo $this->formInput($complemento);
        echo '</div>';

        $bairro = $form->get('bairro');
        echo '<div class="col-md-4">';
        echo $this->formInput($bairro);
        echo '</div>';

        $cidade = $form->get('localidade');
        echo '<div class="col-md-offset-2 col-md-4">';
        echo $this->formInput($cidade);
        echo '</div>';

        $estado = $form->get('uf');
        echo '<div class="col-md-2">';
        echo $this->formInput($estado);
        echo '</div>';

        $cep = $form->get('cep');
        echo '<div class="col-md-4">';
        echo $this->formInput($cep);
        echo '</div>';


        echo '</div>';
        ?>
    </div>


    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <?php
                $submit = $form->get('submit');
                echo $this->formSubmit($submit);
                ?>
            </div>
        </div>
    </div>

    <?php


    echo $this->form()->closeTag();

    foreach ($form as $element) {
        echo $this->formElementErrors($element);
    }
    ?>

</div>