<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            Meu perfil
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nome</dt>
            <dd><?php echo $this->perfil->getTratamento() . ' ' . $this->perfil->getNome() . ' ' . $this->perfil->getSobrenome(); ?></dd>
            <dt>Email</dt>
            <dd><?php echo $this->perfil->getUser(); ?></dd>
            <dt>Telefone</dt>
            <dd><?php // echo $this->perfil->getTelefones() . ' <small><span class="label label-default">' . $this->perfil->getTelefones() . '</span></small>'; ?></dd>
        </dl>
        <hr>
        <dl class="dl-horizontal">
            <dt>Endereço</dt>
            <dd><?php // echo $this->perfil->getEndereco()->getLogradouro() . ', ' . $this->perfil->getEndereco()->getNumero(); ?></dd>
            <dt>Complemento</dt>
            <dd><?php // echo $this->perfil->getEndereco()->getComplemento(); ?></dd>
            <dt>Bairro</dt>
            <dd><?php // echo $this->perfil->getEndereco()->getBairro(); ?></dd>
            <dt>Cidade</dt>
            <dd><?php // echo $this->perfil->getEndereco()->getLocalidade() . '/' . $this->perfil->getEndereco()->GetUf(); ?></dd>
            <dt>CEP</dt>
            <dd><?php // echo $this->perfil->getEndereco()->getCep(); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <a class="btn btn-default"
                   href="<?php echo $this->url('tenil-user/default', array('controller' => 'profile', 'action' => 'edit')) ?>"
                   target="_self">Editar</a>
            </div>
        </div>
    </div>
</div>



