<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $this->translate('Perfis') ?>
            <small><?php echo $this->translate('Administração de perfis') ?></small>
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Apelido</th>
            <th>Editar</th>
            <th>Excluir</th>
            <th>Endereço</th>
            <th>Telefone</th>
        </tr>
        <?php foreach ($this->data as $value): ?>
            <tr>
                <td><?php echo $this->escapeHtml($value->getId()); ?></td>
                <td><?php echo $this->escapeHtml($value->getNome()); ?></td>
                <td><?php echo $this->escapeHtml($value->getSobrenome()); ?></td>
                <td><?php echo $this->escapeHtml($value->getApelido()); ?></td>
                <td>
                    <a href="<?php echo $this->url('perfil/update', array('id' => $value->getId()), true); ?>">Editar</a>
                </td>
                <td>
                    <a href="<?php echo $this->url('perfil/delete', array('id' => $value->getId()), true); ?>">Editar</a>
                </td>

                <td><?php // echo $this->escapeHtml($value->getTelefones()); ?></td>
                <td></td>
            </tr>
        <?php endforeach; ?>
    </table>

    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <a class="btn btn-default"
                   href="<?php echo $this->url('tenil-user/default', array('controller' => 'profile', 'action' => 'create')); ?>"
                   target="_self">Novo</a>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <?php
        // echo  $this->paginationControl($this->data, 'Sliding', 'partials/paginator/control_v2', array('route' => 'tenil-user/paginator'));
        ?>
    </div>
</div>