<?php
$title = $this->translate('Editar Perfil');
$this->headTitle($title);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $title ?>
        </div>
    </div>
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('perfil/update', array(), true));
    $form->setAttributes(array(
        'method' => 'post',
        'role' => 'form',
        'class' => 'form-horizontal',
        'label' => $title
    ));
    $form->prepare();

    echo $this->form()->openTag($form);
    ?>
    <div class="panel-body">
        <?php

        // Elementos do form
        $id         = $form->get('perfil')->get('id');
        $security   = $form->get('security');
        $nome       = $form->get('perfil')->get('nome');
        $sobrenome  = $form->get('perfil')->get('sobrenome');
        $apelido    = $form->get('perfil')->get('apelido');

        // Configurando atributos dos Elementos
        $nome->setLabel('Nome')
            ->setAttribute('placeholder', 'Nome')
            ->setAttribute('class', 'form-control')
            ->setAttribute('required', 'required')
            ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
        $sobrenome->setLabel('Sobrenome')
            ->setAttribute('placeholder', 'Sobrenome')
            ->setAttribute('class', 'form-control')
            ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
        $apelido->setLabel('Apelido')
            ->setAttribute('placeholder', 'Apelido')
            ->setAttribute('class', 'form-control')
            ->setLabelAttributes(array('class' => 'col-md-2 control-label'));

        echo $this->formHidden($id);
        echo $this->formElement($security);
        ?>
        <div class="form-group">
            <?php echo $this->formLabel($nome); ?>
            <div class="col-md-2">
                <label for="temp">Tratamento</label>
                <select id="temp" class="form-control">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                </select>
            </div>
            <div class="col-md-4">
                <?php echo $this->formInput($nome); ?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formInput($sobrenome); ?>
            </div>
            <div class="col-md-4">
                <?php echo $this->formInput($apelido); ?>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <?php
                $submit = $form->get('submit');
                $submit->setAttribute('class', 'btn btn-default');
                echo $this->formSubmit($submit);
                ?>
            </div>
        </div>
    </div>
    <?php

    echo $this->form()->closeTag();

    foreach ($form as $element) {
        echo $this->formElementErrors($element);
    }
    ?>
</div>