<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . '/page/' . $page;
    else
        return preg_replace('/\d/', $page, $urlPattern);
};
?>

<?php if ($this->pageCount): ?>
    <div class="col-md-12 text-center">
        <ul class="pagination">

            <!-- First page link -->
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->first) ?>">Primeira</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">Primeira</a></li>
            <?php endif; ?>

            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->previous) ?>">Anterior</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">Anterior</a></li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $pagina) { ?>
                <?php echo ($this->current === $pagina) ? "<li class=\"disabled\">" : "<li>"; ?><a href="<?php echo $formatUrl($pagina); ?>"><?php echo $pagina; ?></a></li> 
            <?php }; ?>


            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->next); ?>">Próxima</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">Próxima</a></li>
            <?php endif; ?>

            <!-- Last page link -->
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->last); ?>">Última</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">Última</a></li>
            <?php endif; ?>
        </ul> 
        <p class="text-center"><?php echo $this->firstItemNumber; ?>-<?php echo $this->lastItemNumber; ?> de <?php echo $this->totalItemCount; ?></p>
    </div>
<?php endif; ?> 