<?php
/**
 * Annotation para type helper
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \TenilAcl\Form\Role $form
 */
?>
<?php
// Título da página e formulário
$title = $this->translate('Adicionar Privilégio');
$this->headTitle($title);
?>
<?php
// Configurando o formulário
$form = $this->form;
$form->setAttribute('action', $this->url('tenil-acl-admin/default', array('controller' => 'privileges', 'action' => 'add')));
$form->setAttributes(array(
    'method' => 'post',
    'role' => 'form',
    'class' => 'col s12 m10 offset-m1 l8 offset-l2',
    'label' => $title
));

// Elementos do form
$id = $form->get('id');
$security = $form->get('security');
$nome = $form->get('nome');
$role = $form->get('role');
$resource = $form->get('resource');

// Configurando atributos dos Elementos
$nome->setLabel('Privilégio')->setAttribute('class', 'validate');
$role->setLabel('Papel');
$resource->setLabel('Recurso');

$form->prepare();
?>
<div class="section">
    <div class="container">
        <div class="row">
            <?php echo $this->form()->openTag($form); ?>
            <?php
            echo $this->formHidden($id);
            echo $this->formElement($security);
            ?>
            <h3 class="header"><?php echo $this->translate('Adicionar Privilégio') ?></h3>

            <div class="row">
                <div class="input-field col s12 <?php echo($nome->getMessages() ? 'invalid' : ''); ?>">
                    <?php echo $this->formLabel($nome); ?>
                    <?php $nome->setAttribute('class', ($nome->getMessages() ? 'invalid' : '')); ?>
                    <?php echo $this->formInput($nome); ?>
                    <?php // echo $this->formElementErrors($nome); ?>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12 <?php echo($role->getMessages() ? 'invalid' : ''); ?>">
                    <?php echo $this->formSelect($role); ?>
                    <?php echo $this->formElementErrors($role); ?>
                    <?php echo $this->formLabel($role); ?>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12 <?php echo($resource->getMessages() ? 'invalid' : ''); ?>">
                    <?php echo $this->formSelect($resource); ?>
                    <?php echo $this->formElementErrors($resource); ?>
                    <?php echo $this->formLabel($resource); ?>
                </div>
            </div>

            <div class="input-field col s4">
                <?php
                $submit = $form->get('submit');
                $submit->setAttribute('class', 'waves-effect waves-light btn col s12');
                echo $this->formSubmit($submit);
                ?>
            </div>
        </div>

    </div>
</div>