<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $this->translate('Editar privilégio') ?>
        </div>
    </div>
    <?php
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action', $this->url('tenil-acl-admin/default', array('controller' => 'privileges', 'action' => 'edit')));

    echo $this->form()->openTag($form);

    ?>
    <div class="panel-body">
        <?php

        $id = $form->get('id');
        echo $this->formHidden($id);

        $security = $form->get('security');
        echo $this->formElement($security);

        echo '<div class="form-group">';
        $nome = $form->get('nome');
        echo $this->formLabel($nome);
        echo '<div class="col-md-10">';
        echo $this->formInput($nome);
        echo '</div>';
        echo '</div>';


        echo '<div class="form-group">';
        $role = $form->get('role');
        echo $this->formLabel($role);
        echo '<div class="col-md-10">';
        echo $this->formSelect($role);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $resource = $form->get('resource');
        echo $this->formLabel($resource);
        echo '<div class="col-md-10">';
        echo $this->formSelect($resource);
        echo '</div>';
        echo '</div>';

        ?>
    </div>


    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <?php
                $submit = $form->get('submit');
                echo $this->formSubmit($submit);
                ?>
            </div>
        </div>
    </div>

    <?php


    echo $this->form()->closeTag();

    foreach ($form as $element) {
        echo $this->formElementErrors($element);
    }
    ?>

</div>