<?php
/**
 * Annotation para type helper
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
?>


    <div class="section">
        <div class="container">

            <div class="row">
                <div class="col s12">
                    <h3 class="title">
                        <?php echo $this->translate('Privilégios') ?>
                        <small><?php echo $this->translate('Administração de Privilégios (Privileges)') ?></small>
                    </h3>
                </div>
            </div>

            <div class="fixed-action-btn">
                <a class="btn-floating waves-effect waves-light btn-large red"
                   href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'privileges', 'action' => 'add')); ?>">
                    <i class="large material-icons">add</i>
                </a>
            </div>

            <table class="bordered highlight responsive-table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Papel</th>
                    <th>Recurso</th>
                    <th>Privilégio</th>
                    <th>Ações</th>
                    <th>Data</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->data as $value): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($value->getId()); ?></td>
                        <td><?php echo $this->escapeHtml($value->getRole()->getNome()); ?></td>
                        <td><?php echo $this->escapeHtml($value->getResource()->getNome()); ?></td>
                        <td><?php echo $this->escapeHtml($value->getNome()); ?></td>
                        <td>
                            <a class="waves-effect waves-light btn"
                               href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'privileges', 'action' => 'edit', 'id' => $value->getId())) ?>">Editar</a>
                            <a class="waves-effect waves-light btn"
                               href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'privileges', 'action' => 'delete', 'id' => $value->getId())) ?>">Excluir</a>
                        </td>
                        <td>
                            <small><?php
                                echo $this->dateFormat(
                                    $value->getCreatedAt(), IntlDateFormatter::MEDIUM, // date
                                    IntlDateFormatter::SHORT, // time
                                    "pt_BR"
                                );
                                ?></small>
                            <br/>
                            <small><?php
                                echo $this->dateFormat(
                                    $value->getUpdatedAt(), IntlDateFormatter::MEDIUM, // date
                                    IntlDateFormatter::SHORT, // time
                                    "pt_BR"
                                );
                                ?></small>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>


        </div>
    </div>
<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator/paginator-materialize', array('route' => 'tenil-acl-admin/paginator')); ?>