<?php  $container = $this->navigation()->breadcrumbs() ?>
<?php /* @var $container \Zend\View\Helper\Navigation\Breadcrumbs */ ?>
<?php //$navigation = $this->container ?>
<?php /* @var $navigation \Zend\Navigation\Navigation */ ?>
<div class="container">
    <ol class="breadcrumb">
        <li><a href="<?php echo $this->url('home') ?>">Home</a></li>
        <?php foreach ($this->pages as $page): ?>
            <?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
            <?php if (!$page->isActive()): ?>
                <li>
                    <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a>
                </li>
            <?php else: ?>
                <li class="active">
                    <?php if ($container->getLinkLast()): ?><a href="<?php echo $page->getHref() ?>"><?php endif ?>
                        <?php echo $page->getLabel() ?>
                        <?php if ($container->getLinkLast()): ?></a><?php endif ?>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    </ol>
</div>