<?php
$status = array('default', 'success', 'warning', 'error', 'info');

$fm = $this->flashMessenger();
$fm->setNamespace('Tenil');
?>
<div class="container" id="mensagens">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <?php
            /**
             * Percorre os status e gera a mensagem apropriada.
             */
            foreach ($status as $value) {
                $alertClass = 'alert-' . $value;
                if ($value == 'default') {
                    $alertClass = 'alert-info';
                } elseif ($value == 'error') {
                    $alertClass = 'alert-danger';
                }
                echo $fm->renderCurrent($value, array('alert', 'alert-dismissable', $alertClass));
            }
            $fm->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
            foreach ($status as $value) {
                $alertClass = 'alert-' . $value;
                if ($value == 'default') {
                    $alertClass = 'alert-info';
                } elseif ($value == 'error') {
                    $alertClass = 'alert-danger';
                }
                echo $fm->render($value, array('alert', 'alert-dismissable', $alertClass));
            }
            ?>
        </div>
    </div>
</div>