<?php $user = $this->identity(); ?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="<?php echo $this->url('home') ?>" class="navbar-brand">Arcanjo Project</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">
            <ul class="nav navbar-nav">
                <?php foreach ($this->container as $page) { ?>
                    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) {
                        continue;
                    } ?>
                    <?php $hasChildren = $page->hasPages(); ?>
                    <?php if (!$hasChildren) { ?>
                        <li>
                            <a href="<?php echo $page->getHref() ?>">
                                <?php echo $this->translate($page->getLabel()) ?>
                            </a>
                        </li>
                    <?php } else { ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle"
                               data-toggle="dropdown"><?php echo $this->translate($page->getLabel()) ?> <b
                                    class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <?php foreach ($page->getPages() as $child) { ?>
                                    <?php // when using partials we need to manually check for ACL conditions ?>
                                    <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) {
                                        continue;
                                    } ?>
                                    <li>
                                        <a href="<?php echo $child->getHref() ?>">
                                            <?php echo $this->translate($child->getLabel()) ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                <?php } ?>
            </ul>
            <?php if ($user): ?>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url('tenil-perfil/default', array('action' => 'detail')) ?>"><?php echo $user->getEmail(); ?></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('tenil-perfil/default', array('action' => 'detail')) ?>"><?php echo $this->gravatar($user->getEmail())->setImgSize(20)->getImgTag(); ?></a>
                    </li>
                    <li><a href="<?php echo $this->url('tenil-auth/default', array('action' => 'logout')) ?>"
                           data-toggle="tooltip" data-placement="bottom" title="Sair"><span
                                class="glyphicon glyphicon glyphicon-log-out" aria-hidden="true"></span></a></li>
                </ul>
            <?php else : ?>
                <div class="nav navbar-nav navbar-right">
                    <a class="btn btn-default navbar-btn"
                       href="<?php echo $this->url('tenil-auth/default', array('action' => 'login')) ?>"><?php echo $this->translate('Login') ?></a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<?php echo $this->url('tenil-user/default', array('action' => 'register')) ?>"><?php echo $this->translate('Crie sua conta') ?></a>
                    </li>
                </ul>
            <?php endif; ?>
        </nav>
    </div>
</nav>