<div class="container">
    <div class="row">
        <div class="col-md-3" id="leftCol">

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <div class="panel-title">Configurações pessoais</div>
                </div>
                <!-- List group -->
                <div class="list-group">
                    <a href="<?php echo $this->url('perfil/detail') ?>" class="list-group-item">Perfil</a>
                </div>
            </div>

            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <div class="panel-title">Eventos</div>
                </div>
                <!-- List group -->
                <div class="list-group">
                    <a href="<?php echo $this->url('tenil-evento'); ?>" class="list-group-item">Todos os eventos</a>
                    <a href="<?php echo $this->url('tenil-evento/default', array('action' => 'meus-eventos')); ?>" class="list-group-item">Meus eventos</a>
                </div>
            </div>

            <?php if ($this->usuario->getEmail() == 'roberto.tenil@gmail.com'): ?>
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <div class="panel-title">Administrador</div>
                    </div>
                    <!-- List group -->
                    <div class="list-group">
                        <a href="<?php echo $this->url('tenil-user/default', array('controller' => 'users', 'action' => 'index')) ?>" class="list-group-item"><?php echo $this->translate('Usuários') ?></a>
                        <a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles')) ?>" class="list-group-item"><?php echo $this->translate('Roles') ?></a>
                        <a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'resources')) ?>" class="list-group-item"><?php echo $this->translate('Resources') ?></a>
                        <a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'privileges')) ?>" class="list-group-item"><?php echo $this->translate('Privileges') ?></a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-md-9">
            <?php echo $this->content; ?>
        </div> 
    </div>
</div>