<div class="container">
    <div class="row">
        <div class="col-md-3" id="leftCol">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Configurações pessoais</h3>
                </div>
                <div class="panel-body">
                    <ul class="nav nav-stacked" id="sidebar">
                        <li><a href="<?php echo $this->url('tenil-user') ?>">Perfil</a></li>
                        <li><a href="#sec2">Alterar Senha</a></li>
                        <li><a href="#sec3">Endereço</a></li>
                        <li><a href="#sec4">Faturamento</a></li>
                    </ul>
                </div>
            </div>
            <?php if ($this->usuario->getEmail() == 'roberto.tenil@gmail.com'): ?>
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h3 class="panel-title">Administrador</h3>
                    </div>
                    <div class="panel-body">
                        <ul class="nav nav-stacked">
                            <li><a href="<?php echo $this->url('tenil-user/default', array('controller' => 'users', 'action' => 'index')) ?>"><?php echo $this->translate('Usuários') ?></a></li>
                            <li><a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles')) ?>"><?php echo $this->translate('Roles') ?></a></li>
                            <li><a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'resources')) ?>"><?php echo $this->translate('Resources') ?></a></li>
                            <li><a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'privileges')) ?>"><?php echo $this->translate('Privileges') ?></a></li>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        </div>  
        <div class="col-md-9">
            <?php echo $this->content; ?>
        </div> 
    </div>
</div>