<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $this->translate('Conta do usuário') ?>
        </div>
    </div>
    <?php
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action', $this->url('tenil-user/default', array('controller' => 'users', 'action' => 'edit')));

    echo $this->form()->openTag($form);
    ?>
    <div class="panel-body">
        <?php

        $id = $form->get('id');
        echo $this->formHidden($id);

        $security = $form->get('security');
        echo $this->formElement($security);

        echo '<div class="form-group">';
        $nome = $form->get('nome');
        echo $this->formLabel($nome);
        echo '<div class="col-md-10">';
        echo $this->formInput($nome);
        echo '</div>';
        echo '</div>';


        echo '<div class="form-group">';
        $email = $form->get('email');
        echo $this->formLabel($email);
        echo '<div class="col-md-10">';
        echo $this->formInput($email);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $password = $form->get('password');
        echo $this->formLabel($password);
        echo '<div class="col-md-10">';
        echo $this->formInput($password);
        echo '</div>';
        echo '</div>';

        ?>
    </div>

    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <?php
                $submit = $form->get('submit');
                $submit->setAttribute('class', 'btn btn-default');
                echo $this->formSubmit($submit);
                ?>
            </div>
        </div>
    </div>

    <?php


    echo $this->form()->closeTag();

    foreach ($form as $element) {
        echo $this->formElementErrors($element);
    }
    ?>

</div>