<div class="page-header">
    <h1><?php echo $this->translate('Usuários') ?> <small><?php echo $this->translate('Edição') ?></small></h1>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="clearfix"></div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><?php echo $this->translate('Editar Usuário') ?></h2>
            </div>
            <div class="panel-body">
                <?php
                $form = $this->form;
                $form->prepare();

                $form->setAttribute('action', $this->url('tenil-user-admin/default', array('controller' => 'users', 'action' => 'edit')));

                echo $this->form()->openTag($form);

                $id = $form->get('id');
                echo $this->formHidden($id);

                $security = $form->get('security');
                echo $this->formElement($security);

                echo '<div class="form-group">';
                $nome = $form->get('nome');
                echo $this->formLabel($nome);
                echo '<div class="col-lg-10">';
                echo $this->formInput($nome);
//                echo $this->formElementErrors($nome);
                echo '</div>';
                echo '</div>';


                echo '<div class="form-group">';
                $email = $form->get('email');
                echo $this->formLabel($email);
                echo '<div class="col-lg-10">';
                echo $this->formInput($email);
//                echo $this->formElementErrors($email);
                echo '</div>';
                echo '</div>';

                echo '<div class="form-group">';
                $password = $form->get('password');
                echo $this->formLabel($password);
                echo '<div class="col-lg-10">';
                echo $this->formInput($password);
//                echo $this->formElementErrors($password);
                echo '</div>';
                echo '</div>';

                echo '<div class="form-group">';
                $name = $form->get('submit');
                echo '<div class="col-lg-offset-2 col-lg-10">';
                echo $this->formSubmit($name);
                echo '</div>';
                echo '</div>';

                echo $this->form()->closeTag();


                foreach ($form as $element) {
                    echo $this->formElementErrors($element);
                }
                ?>
            </div>

        </div>

    </div>
</div>