<div class="page-header">
    <h1><?php echo $this->translate('Usuários') ?> <small><?php echo $this->translate('Administração de usuários') ?></small></h1>
</div>
<?php foreach ($this->messages as $value): ?>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-dismissable alert-info">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Mensagem:</strong> <?php echo $value; ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<div class="row">
    <div class="col-md-12">
        <p>
            <a class="btn btn-lg btn-default" href="<?php echo $this->url('tenil-user-admin', array('action' => 'new')) ?>" target="_self">Novo</a>
        </p>
    </div>
    <div class="col-md-12">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th>Ação</th>
            </tr>
            <?php foreach ($this->data as $value): ?>
                <tr>
                    <td><?php echo $value->getId(); ?></td>
                    <td><?php echo $value->getNome(); ?></td>
                    <td><?php echo $value->getEmail(); ?></td>
                    <td>N/A</td>
                </tr>
            <?php endforeach; ?>
        </table>
        <?php echo $this->paginationControl($this->data, 'sliding', 'partials/paginator/control'); ?>
    </div>
</div>