<div class="page-header">
    <h1><?php echo $this->translate('Usuários') ?> <small><?php echo $this->translate('Administração de usuários') ?></small></h1>
</div>

<div class="row">
</div>

<div class="row">
    <div class="col-md-12">
        <p>
            <a class="btn btn-lg btn-default" href="<?php echo $this->url('tenil-user/default', array('controller' => 'users', 'action' => 'add')) ?>" target="_self">Novo</a>
        </p>
    </div>
    <div class="col-md-12">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Img</th>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Ativo</th>
                    <th>Editar</th>
                    <th>Excluir</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->data as $value): ?>
                
                    <tr <?php echo $value->getActive() ? 'class="success"' : null; ?>>
                        <td><?php echo $this->escapeHtml($value->getId()); ?></td>
                        <td><?php echo $this->gravatar($value->getEmail())->setImgSize(40)->getImgTag(); ?></td>
                        <td><?php echo $this->escapeHtml($value->getNome()); ?></td>
                        <td><?php echo $this->escapeHtml($value->getEmail()); ?></td>
                        <td><?php echo $value->getActive() ? 'Sim' : 'Não'; ?></td>
                        <td><a href="<?php echo $this->url('tenil-user/default', array('controller' => 'users', 'action' => 'edit')) . '/id/' . $value->getId() ?>">Editar</a></td>
                        <td><a href="<?php echo $this->url('tenil-user/default', array('controller' => 'users', 'action' => 'delete')) . '/id/' . $value->getId() ?>">Excluir</a></td>
                        <td><kbd><?php
                                echo $this->dateFormat(
                                        $value->getCreatedAt(), IntlDateFormatter::MEDIUM, // date
                                        IntlDateFormatter::MEDIUM, // time
                                        "pt_BR"
                                );
                                ?></kbd><br /><kbd><?php
                                echo $this->dateFormat(
                                        $value->getUpdatedAt(), IntlDateFormatter::MEDIUM, // date
                                        IntlDateFormatter::MEDIUM, // time
                                        "pt_BR"
                                );
                                ?></kbd></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php
        echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator/control_v2', array('route' => 'tenil-user/paginator'));
        ?>
    </div>
</div>