<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Sistema Político'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/signin.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <?php
                    $flash = $this->flashMessenger();
                    $flash->setNamespace('TenilUser');

                    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
                    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
                    echo $flash->render('warning', array('alert', 'alert-dismissable', 'alert-warning'));
                    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-info'));
                    ?>            
                </div>
            </div>
        </div> <!-- /container -->        

        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
    </body>
</html>
