<?php
echo $this->translate('isEmpty');
echo $this->translate('notEmptyInvalid');
echo $this->translate('Value is required and can\'t be empty');
echo $this->translate('"Invalid type given. String expected"');
echo $this->translate("Invalid type given. String expected");
echo $this->translate("The input is not a valid email address. Use the basic format local-part@hostname");
echo $this->translate("'%hostname%' is not a valid hostname for the email address");
echo $this->translate("'%hostname%' does not appear to have any valid MX or A records for the email address");
echo $this->translate("'%hostname%' is not in a routable network segment. The email address should not be resolved from public network");
echo $this->translate("'%localPart%' can not be matched against dot-atom format");
echo $this->translate("'%localPart%' can not be matched against quoted-string format");
echo $this->translate("'%localPart%' is not a valid local part for the email address");
echo $this->translate("The input exceeds the allowed length");
echo $this->translate("The input does not match the expected structure for a DNS hostname");
echo $this->translate("The input appears to be a local network name but local network names are not allowed");
echo $this->translate("The form submitted did not originate from the expected site");