<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $this->translate('Papéis') ?>
            <small><?php echo $this->translate('Administração de Papéis (Roles)') ?></small>
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Pai</th>
            <th>É admin?</th>
            <th>Editar</th>
            <th>Excluir</th>
            <th>Data</th>
        </tr>
        <?php foreach ($this->data as $value): ?>
            <tr>
                <td><?php echo $this->escapeHtml($value->getId()); ?></td>
                <td><?php echo $this->escapeHtml($value->getNome()); ?></td>
                <td><?php echo $this->escapeHtml($value->getParent()); ?></td>
                <td><?php echo $this->escapeHtml($value->getIsAdmin() ? 'Sim' : 'Não'); ?></td>
                <td>
                    <a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles', 'action' => 'edit', 'id' => $value->getId())) ?>">Editar</a>
                </td>
                <td>
                    <a href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles', 'action' => 'delete', 'id' => $value->getId())) ?>">Excluir</a>
                </td>
                <td>
                    <small><?php
                        echo $this->dateFormat(
                            $value->getCreatedAt(), IntlDateFormatter::MEDIUM, // date
                            IntlDateFormatter::SHORT, // time
                            "pt_BR"
                        );
                        ?></small>
                    <br/>
                    <small><?php
                        echo $this->dateFormat(
                            $value->getUpdatedAt(), IntlDateFormatter::MEDIUM, // date
                            IntlDateFormatter::SHORT, // time
                            "pt_BR"
                        );
                        ?></small>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <div class="panel-footer">
        <div class="clearfix">
            <div class="pull-right">
                <a class="btn btn-default"
                   href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles', 'action' => 'add')); ?>"
                   target="_self">Novo</a>
            </div>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <?php
        echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator/control_v2', array('route' => 'tenil-acl-admin/paginator'));
        ?>
    </div>
</div>


