<?php
/**
 * Annotation para type helper
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
?>
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <h3 class="title">
                        <?php echo $this->translate('Papéis') ?>
                        <small><?php echo $this->translate('Administração de Papéis (Roles)') ?></small>
                    </h3>
                </div>
            </div>
            <div class="row">
                <div class="col s12 right-align">
                    <a class="btn-floating btn-large waves-effect waves-light red "
                       href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles', 'action' => 'add')); ?>"
                       target="_self"><i class="material-icons">add</i>Novo</a>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Pai</th>
                            <th>Ações</th>
                            <th>Data</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->data as $value): ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($value->getId()); ?></td>
                                <td><?php echo $this->escapeHtml($value->getNome()); ?></td>
                                <td><?php echo $this->escapeHtml($value->getParent()); ?></td>
                                <td>
                                    <a class="waves-effect waves-light btn"
                                       href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles', 'action' => 'edit', 'id' => $value->getId())) ?>">Editar</a>
                                    <a class="waves-effect waves-light btn"
                                       href="<?php echo $this->url('tenil-acl-admin/default', array('controller' => 'roles', 'action' => 'delete', 'id' => $value->getId())) ?>">Excluir</a>
                                </td>
                                <td>
                                    <small><?php
                                        echo $this->dateFormat(
                                            $value->getCreatedAt(), IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
                                            "pt_BR"
                                        );
                                        ?></small>
                                    <br/>
                                    <small><?php
                                        echo $this->dateFormat(
                                            $value->getUpdatedAt(), IntlDateFormatter::MEDIUM, // date
                                            IntlDateFormatter::SHORT, // time
                                            "pt_BR"
                                        );
                                        ?></small>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator/paginator-materialize', array('route' => 'tenil-acl-admin/paginator')); ?>