<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Convenção 2015 <small>Inscrições</small></h3>
    </div>
    <div class="panel-body">
        <p>Faça aqui a sua inscrição para a Convenção Mundial 2015.</p>
        <p>
            <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="right" title="Faça sua inscrição.">Clique aqui</button>
        </p>
    </div>
</div>