<?php
/**
 * Annotation para type helper
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \TenilEvento\Form\EventoCreate $form
 */
?>
<?php
// Título da página e formulário
$title = $this->translate('Novo evento');
$this->headTitle($title);
?>
<?php
// Configurando o formulário
$form = $this->form;
$form->setAttribute('action', $this->url('tenil-evento/create', array('action' => 'create')));

$form->setAttributes(array(
    'method' => 'post',
    'role' => 'form',
    'class' => 'col s12 m10 offset-m1 l8 offset-l2',
    'label' => $title
));

$form->prepare();

// Elementos do form
$id = $form->get('evento')->get('id');
$security = $form->get('security');
$nome = $form->get('evento')->get('nome');
$tema = $form->get('evento')->get('tema');
$dataInicio = $form->get('evento')->get('dataInicio');
$dataFim = $form->get('evento')->get('dataFim');
$descricao = $form->get('evento')->get('descricao');
$email = $form->get('evento')->get('email');
$horaInicio = $form->get('evento')->get('horaInicio');
$horaFim = $form->get('evento')->get('horaFim');
$organizador = $form->get('evento')->get('organizador');
$qtdVagas = $form->get('evento')->get('qtdVagas');
$valorInscricao = $form->get('evento')->get('valorInscricao');
$flagEventoGratuito = $form->get('evento')->get('flagEventoGratuito');
$flagInscricoesAbertas = $form->get('evento')->get('flagInscricoesAbertas');
// $slug = $form->get('evento')->get('slug');

$submit = $form->get('submit');

// Configurando atributos dos Elementos


$nome->setLabel('Título')
    //->setAttribute('placeholder', 'Nome')
    ->setAttribute('class', 'validate')//->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$tema->setLabel('Tema')
    //->setAttribute('placeholder', 'Tema')
    //->setAttribute('class', 'form-control')
    //->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$descricao->setLabel('Descrição')
    //->setAttribute('placeholder', 'Descrição')
    ->setAttribute('class', 'materialize-textarea')//->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$dataInicio->setLabel('Data de início')
    ->setAttribute('placeholder', 'DD/MM/AAAA')
    //->setAttribute('class', 'datepicker')// ->setLabelAttributes(array('class' => 'col-md-3 control-label'))
    ->setAttribute('id', 'data-evento-inicio');
$dataFim->setLabel('Data de término')
    ->setAttribute('placeholder', 'DD/MM/AAAA')
    //->setAttribute('class', 'datepicker')
    //->setLabelAttributes(array('class' => 'col-md-3 control-label'))
    ->setAttribute('id', 'data-evento-termino');
$horaInicio->setLabel('Hora de início')
    //->setAttribute('placeholder', 'Hora de início')
    //->setAttribute('class', 'timepicker')
    //->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$horaFim->setLabel('Hora de encerramento')
    // ->setAttribute('placeholder', 'Hora de encerramento')
    // ->setAttribute('class', 'form-control')
    //->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$flagInscricoesAbertas->setLabel('Inscrições abertas')
    // ->setAttribute('placeholder', 'Inscrições abertas')
    //->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$organizador->setLabel('Organizador do evento')
    // ->setAttribute('placeholder', 'Organizador ou produtor do evento')
    // ->setAttribute('class', 'form-control')
    // ->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$email->setLabel('E-mail para contato')
    // ->setAttribute('placeholder', 'E-mail para contato')
    // ->setAttribute('class', 'form-control')
    // ->setLabelAttributes(array('class' => 'col-md-3 control-label'))
;
$submit->setAttribute('class', 'btn btn-primary');

/*
$telefones->setLabel('Telefone')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
$enderecos->setLabel('Endereço')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
$tratamento->setLabel('Tratamento')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
$submit->setAttribute('class', 'btn btn-default');
*/
// Configurando Elemento de erro
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="row"><div class="col s12">')
    ->setMessageSeparatorString('</div><div class="col s12">')
    ->setMessageCloseString('</div></div>');
?>
<div class="section">
    <div class="container">
        <div class="row">
            <?php echo $this->form()->openTag($form); ?>
            <?php
            echo $this->formHidden($id);
            echo $this->formElement($security);
            ?>
            <h3 class="header">Detalhes do Evento</h3>
            <div class="row">
                <div class="input-field col s12 <?php echo($nome->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($nome); ?>
                    <?php echo $this->formInput($nome); ?>
                    <?php echo $this->formElementErrors($nome); ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 <?php echo($tema->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($tema); ?>
                    <?php echo $this->formInput($tema); ?>
                    <?php echo $this->formElementErrors($tema); ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 <?php echo($descricao->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($descricao); ?>
                    <?php echo $this->formTextarea($descricao); ?>
                    <?php echo $this->formElementErrors($descricao); ?>
                </div>
            </div>
            <div class="row">
                <div class="col s12 m6 l3 <?php echo($dataInicio->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($dataInicio); ?>
                    <?php echo $this->formInput($dataInicio); ?>
                    <?php echo $this->formElementErrors($dataInicio); ?>
                </div>
                <div class="col s12 m6 l3 <?php echo($horaInicio->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($horaInicio); ?>
                    <?php echo $this->formSelect($horaInicio); ?>
                    <?php echo $this->formElementErrors($horaInicio); ?>
                </div>
                <div class="col s12 m6 l3 <?php echo($dataFim->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($dataFim); ?>
                    <?php echo $this->formInput($dataFim); ?>
                    <?php echo $this->formElementErrors($dataFim); ?>
                </div>
                <div class="col s12 m6 l3 <?php echo($horaFim->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($horaFim); ?>
                    <?php echo $this->formSelect($horaFim); ?>
                    <?php echo $this->formElementErrors($horaFim); ?>
                </div>
            </div>
            <div class="row">
                <div
                    class="col s12 m6 l3 <?php echo($flagInscricoesAbertas->getMessages() ? 'has-error' : ''); ?>">
                    <p>Inscrições Abertas</p>
                    <!-- Switch -->
                    <div class="switch">
                        <label>
                            Não
                            <?php echo $this->formCheckbox($flagInscricoesAbertas); ?>
                            <span class="lever"></span>
                            Sim
                        </label>
                    </div>
                    <?php echo $this->formElementErrors($flagInscricoesAbertas); ?>
                </div>
            </div>
            <div class="row">
                <h3 class="header">Informações de contato</h3>
                <div class="input-field col s12 <?php echo($organizador->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($organizador); ?>
                    <?php echo $this->formInput($organizador); ?>
                    <?php echo $this->formElementErrors($organizador); ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 <?php echo($email->getMessages() ? 'has-error' : ''); ?>">
                    <?php echo $this->formLabel($email); ?>
                    <?php echo $this->formEmail($email); ?>
                    <?php echo $this->formElementErrors($email); ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s4">
                    <a href="<?php echo $this->url('tenil-evento/default') ?>"
                       class="waves-effect waves-light btn col s12">Cancelar</a>
                </div>
                <div class="input-field col s4">
                    <?php
                    $submit = $form->get('submit');
                    $submit->setAttribute('class', 'waves-effect waves-light btn col s12');
                    echo $this->formSubmit($submit);
                    ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>