<?php
// Título da página
$title = $this->translate('Informações do evento');
$this->headTitle($title);
$evento = $this->data;
?>
<div class="row evento-banner">
    <div class="col-xs-12 hidden-sm hidden-md hidden-lg">
        <img class="img-responsive img-rounded" src="/images/manual/convencao-mundial-2016-banner-1080x1080.png"/>
        <!--Mobile-->
    </div>

    <div class="hidden-xs col-sm-12 col-md-12 col-lg-12">
        <img class="img-responsive img-rounded" src="/images/manual/convencao-mundial-2016-banner-1280x400.jpg"/>
        <!--Tab--> <!--Desktop--> <!--Large-->
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-8">
        <div class="page-header">
            <h1><?php echo $evento->getNome(); ?> <br>
                <small><?php echo $evento->getTema(); ?></small>
            </h1>
        </div>
        <div class="lead">
            <?php echo $evento->getDescricao(); ?>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <table class="table">
                <tbody>
                <tr>
                    <td>Detalhes</td>
                </tr>
                </tbody>
            </table>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>Início</dt>
                    <dd><?php echo $evento->getDataInicio()->format("d/m/Y"); ?></dd>
                    <dt>Final</dt>
                    <dd><?php echo $evento->getDataFim()->format("d/m/Y"); ?></dd>
                </dl>
            </div>
            <table class="table">
                <tbody>
                <tr>
                    <td>Informações</td>
                </tr>
                </tbody>
            </table>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>Organizador</dt>
                    <dd><?php echo $evento->getOrganizador(); ?></dd>
                    <dt>E-mail</dt>
                    <dd><?php echo $evento->getEmail(); ?></dd>
                </dl>
            </div>
            <div class="panel-footer">
                <div class="clearfix">
                    <div class="btn-toolbar pull-right" role="toolbar">
                        <div class="btn-group" role="group">
                            <a href="<?php echo $this->url('tenil-evento/default') ?>"
                               class="btn btn-danger">Cancelar</a>
                            <a href="<?php echo $this->url('tenil-evento/default', array('action' => 'signup', 'id' => $evento->getSlug())) ?>"
                               class="btn btn-primary">Fazer Inscrição</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>