<?php
// Título da página e formulário
$title = $this->translate('Inscrição');
$this->headTitle($title);
$inscricao = $this->data;
?>
<div class="row">
    <div class="col-md-12">
        <div class="page-header">
            <h1><?php echo $inscricao->getEvento(); ?> <br/>
                <small><?php echo $inscricao->getEvento()->getTema(); ?></small>
            </h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-push-6">
        <div class="jumbotron">
            <h1 class="text-center"><?php echo $inscricao->getId(); ?></h1>
        </div>
    </div>
    <div class="col-md-6 col-md-pull-6">
        <div class="lead">
            <p>Olá <?php echo strtok($inscricao, ' '); ?>, <strong>guarde</strong> o número da sua inscrição para
                consultas futuras.</p>
            <p>Gere o boleto e efetue o pagamento dentro do prazo de vencimento.</p>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="btn-toolbar" role="toolbar">
                    <div class="btn-group pull-right" role="group">
                        <a class="btn btn-primary btn-lg"
                           href="<?php echo $this->url('tenil-evento', array('controller' => 'evento', 'action' => 'boleto', 'id' => $inscricao->getId())) ?>"
                           role="button">Gerar boleto</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>



