<?php
// Título da página e formulário
$title = $this->translate('Inscrição');
$this->headTitle($title);
$inscricao = $this->data;
?>
<div class="row">
    <div class="col-md-6">
        <h2><?php echo $inscricao->getEvento(); ?> <br/>
            <small><?php echo $inscricao->getEvento()->getTema(); ?></small>
        </h2>
    </div>
</div>

<div class="row">

    <div class="col-md-6">
        <div class="jumbotron">
            <h1 class="text-center"><?php echo $inscricao->getId(); ?></h1>
        </div>
    </div>
    <div class="col-md-6">
        <p>Olá <?php echo strtok($inscricao, ' '); ?>, anote o número da sua inscrição para consultas futuras.</p>
        <p>Gere o boleto e efetue o pagamento dentro do prazo de vencimento.</p>
        <p><a class="btn btn-primary btn-lg"
              href="<?php echo $this->url('tenil-evento', array('controller' => 'evento', 'action' => 'boleto', 'id' => $inscricao->getId())) ?>"
              role="button">Gerar boleto</a></p>
    </div>

</div>



