<?php
$title = $this->translate('Eventos');
$this->headTitle($title);
$data = $this->data;
?>
<?php foreach ($data as $evento): ?>
    <div class="row">
        <div class="col-md-12">
            <h1><?php echo $evento->getNome(); ?> <br>
                <small><?php echo $evento->getTema(); ?></small>
            </h1>
        </div>
        <div class="col-md-12"><p class="lead"><?php echo $evento->getDataInicio()->format("d/m/Y"); ?>
                - <?php echo $evento->getDataFim()->format("d/m/Y"); ?></p></div>
        <div class="col-md-12">
            <div class="btn-toolbar pull-right" role="toolbar">
                <div class="btn-group" role="group">
                    <a href="<?php echo $this->url('tenil-evento/default', array('action' => 'signup', 'id' => $evento->getSlug())) ?>"
                       class="btn btn-primary">Mais informações</a>
                </div>
            </div>
        </div>
    </div>
    <hr>
<?php endforeach; ?>
<div class="row">
    <div class="col-md-12">
        <?php
        echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator/control_v2', array('route' => 'tenil-evento/paginator'));
        ?>
    </div>
</div>