<?php // $this->headLink()->appendStylesheet('/css/material.min.css'); ?>
<?php $dataInicio = $this->dateFormat($evento->getDataInicio(), IntlDateFormatter::LONG, IntlDateFormatter::NONE, "pt_BR"); ?>
<div class="row evento-banner">
    <div class="col-xs-12 hidden-sm hidden-md hidden-lg"> <!--Mobile-->
        <img class="img-responsive img-rounded" src="/images/manual/convencao-mundial-2016-banner-1080x1080.png"/>

    </div>
    <div class="hidden-xs col-sm-12 col-md-12 col-lg-12"> <!--Tab--> <!--Desktop--> <!--Large-->
        <img class="img-responsive img-rounded" src="/images/manual/convencao-mundial-2016-banner-1280x400.jpg"/>

    </div>
</div>

<?php /*
<div class="row evento-dados">
    <div class="col-md-2">
        <span aria-label="<?php echo $dataInicio ?>" title="<?php echo $dataInicio; ?>">
            <span class="mdl-typography--display-2 mdl-typography--text-uppercase"><?php echo $evento->getDataInicio()->format("d M"); ?></span>
        </span>
    </div>
    <div class="col-md-8 mdl-typography--text-center">
        <span class="mdl-typography--display-1"><?php echo $evento->getNome(); ?></span>
    </div>
    <div class="col-md-2 mdl-typography--text-right">
        <span class="mdl-typography--display-1"><?php echo $this->currencyFormat($evento->getValorInscricao(), "BRL", null, "pt_BR"); ?></span>
    </div>
</div>
 */