<?php
$dataInicio = $this->dateFormat($evento->getDataInicio(), IntlDateFormatter::LONG, IntlDateFormatter::NONE, "pt_BR");
$dimensao = '896x504';
$extensao = '.jpg'
?>
<div class="section uiGradient-Politics">
    <div class="container">
        <div class="row banner-row">
            <div class="col s12 m8 l8">
                <img class="responsive-img z-depth-2 fade-image"
                     src="<?php echo $this->basePath() . "/images/eventos/" . $evento->getSlug() . "/" . $evento->getSlug() . "-banner-" . $dimensao . $extensao ?>"
                     alt="<?php echo $evento->getNome(); ?>">
            </div>
            <div class="col s12 m4 l4 white-text">
                <div class="data-container">
                    <div class="data-mes"><?php echo strtoupper($evento->getDataInicio()->format("M")); ?></div>
                    <div class="data-dia"><?php echo strtoupper($evento->getDataInicio()->format("d")); ?></div>
                </div>
                <h3><?php echo $evento->getNome(); ?></h3>
                <h5><?php echo $evento->getTema(); ?></h5>
                <p><?php echo $evento->getOrganizador(); ?></p>
                <p><?php echo $this->currencyFormat($evento->getValorInscricao(), "BRL", null, "pt_BR", 'R$ #0.#'); ?></p>
            </div>
        </div>
    </div>
</div>