<div class="section">
    <div class="container">
        <div class="row">
            <div class="col s12 m8">
                <h4 class="light red-text text-lighten-1">Descrição</h4>
                <blockquote>
                    <h5 class="header light red-text text-lighten-1"><?php echo $evento->getNome(); ?>
                        - <?php echo $evento->getTema(); ?></h5>
                </blockquote>
                <p>Data: <?php echo $evento->getDataInicio()->format("d.m.Y"); ?>
                    a <?php echo $evento->getDataFim()->format("d.m.Y"); ?></p>
                <p>Local: </p>
                <p class="flow-text"><?php echo $evento->getDescricao(); ?></p>
            </div>
            <div class="col s12 m4">
                <h4 class="light red-text text-lighten-1">Localização</h4>
                <p>Centro de Convenções Ulysses Guimarães<br>
                    Brasília, DF<br>
                    Ver mapa</p>

                <h4 class="light red-text text-lighten-1">Organizador</h4>
                <p><?php echo $evento->getOrganizador(); ?></p>
                <p><?php echo $evento->getEmail(); ?></p>
            </div>
        </div>
    </div>
</div>