<?php
// Título da página e formulário
$title = $this->translate($form->getLabel());
$this->headTitle($title);
?>
<?php
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="col-md-9 col-md-offset-3"><span id="helpBlock" class="help-block">')
    ->setMessageSeparatorString('</span><span id="helpBlock" class="help-block">')
    ->setMessageCloseString('</span></div>');
?>

    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1><?php echo $title ?> <br/>
                </h1>
            </div>
        </div>
    </div>


<?php $form->prepare(); // The correct enctype is set here ?>
<?php echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-md-12">

            <?php $security = $form->get('security'); ?>
            <?php echo $this->formElement($security); ?>

            <?php $fileElement = $form->get('arquivo'); ?>
            <?php $fileElement->setLabel('Arquivo')
                ->setAttribute('placeholder', 'Arquivo')
                ->setAttribute('class', 'form-control')
                ->setLabelAttributes(array('class' => 'col-md-3 control-label')); ?>
            <div class="form-group <?php echo($fileElement->getMessages() ? 'has-error' : ''); ?>">
                <?php echo $this->formLabel($fileElement); ?>
                <div class="col-md-6">
                    <?php echo $this->formFile($fileElement); ?>
                </div>
                <?php echo $this->formElementErrors($fileElement); ?>

            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="btn-toolbar pull-right" role="toolbar">
                <?php $submit = $form->get('submit'); ?>
                <?php $submit->setAttribute('class', 'btn btn-primary btn-lg'); ?>
                <?php echo $this->formSubmit($submit); ?>
            </div>
        </div>
    </div>
<?php echo $this->form()->closeTag(); ?>

<div class="row">
    <div class="col-md-12">
            <?php // var_dump($data); ?>
    </div>
</div>

