<?php
// Título da página e formulário
$title = $this->translate('Nova Inscrição');
$this->headTitle($title);
$evento = $this->data;
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title"><?php echo $evento->getNome(); ?>
            <span class="pull-right"><?php echo $evento->getTema(); ?></span>
        </h1>
    </div>

    <div class="panel-body">

        <dl class="dl-horizontal">
            <dt>Data início</dt>
            <dd><?php
                echo $this->dateFormat(
                    $evento->getDataInicio(),
                    IntlDateFormatter::MEDIUM, // date
                    IntlDateFormatter::NONE, // time
                    "pt_BR"
                );
                ?>
            </dd>
            <dt>Data encerramento</dt>
            <dd><?php
                echo $this->dateFormat(
                    $evento->getDataFim(),
                    IntlDateFormatter::MEDIUM, // date
                    IntlDateFormatter::NONE, // time
                    "pt_BR"
                );
                ?></dd>
            <dt>Sinópse</dt>
            <dd class="text-justify"><?php echo $evento->getDescricao(); ?></dd>
            <dt>Site do evento (slug)</dt>
            <dd><a href="<?php echo $this->url('tenil-evento', array('controller' => 'evento', 'action' => 'detail', 'id' => $evento->getSlug())) ?>"
                   target="_self"><?php echo $evento->getSlug() ?></a></dd>
        </dl>
    </div>
</div>

<?php
// Configurando o formulário
$form = $this->form;
$form->setAttribute('action', $this->url('tenil-evento', array('action' => 'signup', 'id' => $evento->getSlug() )));

$form->setAttributes(array(
    'method' => 'post',
    'role' => 'form',
    'class' => 'form-horizontal',
    'label' => $title
));
$form->prepare();

// Elementos do form
$id = $form->get('inscricao')->get('id');
$security = $form->get('security');
$nome = $form->get('inscricao')->get('nome');
$email = $form->get('inscricao')->get('email');
$cpf = $form->get('inscricao')->get('cpf');
$foneFixo = $form->get('inscricao')->get('foneFixo');
$foneCelular = $form->get('inscricao')->get('foneCelular');
$dataNascimento = $form->get('inscricao')->get('dataNascimento');
$logradouro = $form->get('inscricao')->get('logradouro');
$numero = $form->get('inscricao')->get('numero');
$bairro = $form->get('inscricao')->get('bairro');
$cidade = $form->get('inscricao')->get('localidade');
$uf = $form->get('inscricao')->get('uf');
$cep = $form->get('inscricao')->get('cep');

$submit = $form->get('submit');

// Configurando atributos dos Elementos


$nome->setLabel('Nome')
    ->setAttribute('placeholder', 'Nome')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$email->setLabel('E-mail')
    ->setAttribute('placeholder', 'E-mail')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$cpf->setLabel('CPF')
    ->setAttribute('placeholder', 'CPF')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$dataNascimento->setLabel('Data de nascimento')
    ->setAttribute('placeholder', 'Data de nascimento')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$foneFixo->setLabel('Telefone fixo')
    ->setAttribute('placeholder', 'Telefone fixo com DDD')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$foneCelular->setLabel('Telefone celular')
    ->setAttribute('placeholder', 'Telefone celular com DDD')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$logradouro->setLabel('Endereço')
    ->setAttribute('placeholder', 'Endereço completo')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$numero->setLabel('Número')
    ->setAttribute('placeholder', 'Número')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$bairro->setLabel('Bairro')
    ->setAttribute('placeholder', 'Bairro')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$cidade->setLabel('Cidade')
    ->setAttribute('placeholder', 'Cidade')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$uf->setLabel('UF')
    ->setAttribute('placeholder', 'UF')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$cep->setLabel('CEP')
    ->setAttribute('placeholder', 'CEP')
    ->setAttribute('class', 'form-control')
    ->setLabelAttributes(array('class' => 'col-md-3 control-label'));
$submit->setAttribute('class', 'btn btn-primary');

// Configurando Elemento de erro
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="col-md-10 col-md-offset-2"><span id="helpBlock" class="help-block">')
    ->setMessageSeparatorString('</span><span id="helpBlock" class="help-block">')
    ->setMessageCloseString('</span></div>');
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <div class="panel-title">
            <?php echo $title ?>
        </div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="panel-body">
        <?php
        echo $this->formHidden($id);
        echo $this->formElement($security);
        ?>
        <div class="alert alert-info">Dados pessoais</div>
        <div class="form-group <?php echo($nome->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($nome); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($nome); ?>
            </div>
            <?php echo $this->formElementErrors($nome); ?>
        </div>
        <div class="form-group <?php echo($cpf->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($cpf); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($cpf); ?>
            </div>
            <?php echo $this->formElementErrors($cpf); ?>
        </div>

        <div class="form-group <?php echo($email->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($email); ?>

            <div class="col-md-9">
                <?php echo $this->formEmail($email); ?>
            </div>
            <?php echo $this->formElementErrors($email); ?>
        </div>

        <div class="form-group <?php echo($dataNascimento->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($dataNascimento); ?>

            <div class="col-md-3">
                <?php echo $this->formDate($dataNascimento); ?>
            </div>
            <?php echo $this->formElementErrors($dataNascimento); ?>
        </div>

        <div class="form-group <?php echo($foneCelular->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($foneCelular); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($foneCelular); ?>
            </div>
            <?php echo $this->formElementErrors($foneCelular); ?>
        </div>

        <div class="form-group <?php echo($foneFixo->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($foneFixo); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($foneFixo); ?>
            </div>
            <?php echo $this->formElementErrors($foneFixo); ?>
        </div>



        <div class="alert alert-info">Endereço</div>
        <div class="form-group <?php echo($logradouro->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($logradouro); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($logradouro); ?>
            </div>
            <?php echo $this->formElementErrors($logradouro); ?>
        </div>

        <div class="form-group <?php echo($numero->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($numero); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($numero); ?>
            </div>
            <?php echo $this->formElementErrors($numero); ?>
        </div>

        <div class="form-group <?php echo($bairro->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($bairro); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($bairro); ?>
            </div>
            <?php echo $this->formElementErrors($bairro); ?>
        </div>

        <div class="form-group <?php echo($cidade->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($cidade); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($cidade); ?>
            </div>
            <?php echo $this->formElementErrors($cidade); ?>
        </div>

        <div class="form-group <?php echo($uf->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($uf); ?>

            <div class="col-md-9">
                <?php echo $this->formSelect($uf); ?>
            </div>
            <?php echo $this->formElementErrors($uf); ?>
        </div>

        <div class="form-group <?php echo($cep->getMessages() ? 'has-error' : ''); ?>">
            <?php echo $this->formLabel($cep); ?>

            <div class="col-md-9">
                <?php echo $this->formInput($cep); ?>
            </div>
            <?php echo $this->formElementErrors($cep); ?>
        </div>

    </div>

    <div class="panel-footer">
        <div class="clearfix">
            <div class="btn-toolbar pull-right" role="toolbar">
                <div class="btn-group" role="group">
                    <a href="<?php echo $this->url('tenil-evento') ?>"
                       class="btn btn-danger">Cancelar</a>
                    <?php echo $this->formSubmit($submit); ?>
                </div>
            </div>
        </div>
    </div>
</div>