<?php
/**
 * @var $perfil TenilUser\Entity\Perfil
 */
$email = $this->perfil->getUser()->getEmail();
$settings = array(
    'img_size' => 160,
    'default_img' => \Zend\View\Helper\Gravatar::DEFAULT_MM,
    'rating' => \Zend\View\Helper\Gravatar::RATING_G,
    'secure' => null,
);
$attr = array(
    'class' => 'img-rounded',
    'id' => 'gravatar',
);
$gravatar = $this->gravatar($email, $settings, $attr);
?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Seu perfil</h3>
    </div>
    <div class="panel-body">
        <div class="media">
            <div class="media-left">
                <a href="#">
                    <?php echo $gravatar ?>
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">Foto do perfil</h4>
                <p>Nam vitae libero elementum, varius odio nec, condimentum quam. Vestibulum laoreet massa vitae feugiat rhoncus. Duis viverra dui id blandit convallis. Vivamus nec risus accumsan nisl tincidunt convallis. Praesent nec cursus leo. Nunc risus orci, mollis ac nisl maximus, bibendum ultrices neque. Vivamus sit amet nisi sollicitudin, rhoncus urna non, dapibus augue. Aenean venenatis cursus maximus. Aliquam facilisis quis elit id ullamcorper. Quisque et elit nec leo pellentesque auctor.</p>
            </div>
        </div>
        <hr>
        <dl class="dl-horizontal">
            <dt>Nome</dt><dd><?php echo $this->perfil->getTratamento()->getAbreviacao() . ' ' . $this->perfil->getNome() . ' ' . $this->perfil->getSobrenome(); ?></dd>
            <dt>Email</dt><dd><?php echo $this->perfil->getUser()->getEmail(); ?></dd>
            <dt>Telefone</dt><dd><?php echo '(' . $this->perfil->getFone1ddd() . ') ' . $this->perfil->getFone1Numero() . ' <small>' . $this->perfil->getFone1Tipo()->getNome() . ' </small>'; ?></dd>
            <dt>Telefone</dt><dd><?php echo '(' . $this->perfil->getFone2ddd() . ') ' . $this->perfil->getFone2Numero() . ' <small>' . $this->perfil->getFone2Tipo()->getNome() . ' </small>'; ?></dd>
            <dt>Telefone</dt><dd><?php echo '(' . $this->perfil->getFone3ddd() . ') ' . $this->perfil->getFone3Numero() . ' <small>' . $this->perfil->getFone3Tipo()->getNome() . ' </small>'; ?></dd>
        </dl>
        <hr>
        <dl class="dl-horizontal">
            <dt>Endereço</dt><dd><?php echo $this->perfil->getLogradouro() . ', ' . $this->perfil->getNumero(); ?></dd>
            <dt>Complemento</dt><dd><?php echo $this->perfil->getComplemento(); ?></dd>
            <dt>Bairro</dt><dd><?php echo $this->perfil->getBairro(); ?></dd>
            <dt>Cidade</dt><dd><?php echo $this->perfil->getLocalidade() . '/' . $this->perfil->GetUf(); ?></dd>
            <dt>CEP</dt><dd><?php echo $this->perfil->getCep(); ?></dd>
        </dl>
    </div>
</div>



