<?php
$title = $this->escapeHtml($this->translate('Crie sua conta'));
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user/register'));

$this->formElementErrors()
    ->setMessageOpenFormat('<span id="helpBlock" class="help-block">')
    ->setMessageSeparatorString('</span><span id="helpBlock" class="help-block">')
    ->setMessageCloseString('</span>');

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);

echo $formLabel->openTag() . $form->getAttribute('label') . $formLabel->closeTag();

$security = $form->get('security');
echo $this->formInput($security);

$email = $form->get('user')->get('email');
$email->setAttribute('autofocus', 'autofocus');
echo $this->formInput($email);

$nome = $form->get('user')->get('perfil')->get('nome');
$nome->setAttribute('placeholder', 'Nome')
    ->setAttribute('class', 'form-control')
    ->setAttribute('aria-described-by', 'helpBlock')
    ->setLabelAttributes(array('class' => 'col-md-2 control-label'));
echo $this->formInput($nome);
echo $this->formElementErrors($nome);

$password = $form->get('user')->get('password');
echo $this->formInput($password);

$name = $form->get('submit');
echo $this->formSubmit($name);
?>
<div class="footer">
    <p>Ao inscrever-se, você concorda com os <a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'forgot')) ?>">Termos de Serviço</a></p>
    <p><strong>Já tem uma conta? <a href="<?php echo $this->url('tenil-user/login') ?>">Entre</a></strong></p>
</div>

<?php echo $this->form()->closeTag(); ?>