<?php foreach ($this->messages as $value): ?>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Mensagem:</strong> <?php echo $value; ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
<div class="row">
    <div class="col-md-6">
        <h1><?php echo $this->translate('Bem-vindo') ?></h1>
        <blockquote class="pull-right">
            <p class="lead">No <strong>Sistema Político</strong> você pode gerenciar seu cadastro de eleitores e amigos para potencializar usa campanha e o atendimento no gabinete.</p>
        </blockquote>
        <div class="clearfix"></div>
        <blockquote>
            <p class="lead">Esse é o sistema ideal para canditados e políticos já eleitos.</p>
        </blockquote>
    </div>
    <div class="col-md-6">
        <div class="clearfix"></div>
        <h1><?php echo $this->translate('Crie uma conta') ?></h1>
        <h3><?php echo $this->translate('Comece a usar agora.') ?></h3>
        <?php
        $form = $this->form;
        $form->prepare();

        $form->setAttribute(
                'action', $this->url('tenil-user-register'), array(
            'controller' => 'index',
            'action' => 'register'
                )
        );

        echo $this->form()->openTag($form);

        $id = $form->get('id');
        echo $this->formHidden($id);

        $security = $form->get('security');
        echo $this->formElement($security);

        echo '<div class="form-group">';
        $nome = $form->get('nome');
        echo $this->formLabel($nome);
        echo '<div class="col-lg-10">';
        echo $this->formInput($nome);
        echo $this->formElementErrors($nome);
        echo '</div>';
        echo '</div>';


        echo '<div class="form-group">';
        $email = $form->get('email');
        echo $this->formLabel($email);
        echo '<div class="col-lg-10">';
        echo $this->formInput($email);
        echo $this->formElementErrors($email);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $password = $form->get('password');
        echo $this->formLabel($password);
        echo '<div class="col-lg-10">';
        echo $this->formInput($password);
        echo $this->formElementErrors($password);
        echo '</div>';
        echo '</div>';

        echo '<div class="form-group">';
        $name = $form->get('submit');
        echo '<div class="col-lg-offset-2 col-lg-10">';
        echo $this->formSubmit($name);
        echo '</div>';
        echo '</div>';

        echo $this->form()->closeTag();
        ?>
    </div>
</div>