<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'reset')));

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
echo $formLabel->openTag() . $form->getAttribute('label') . $formLabel->closeTag();

$security = $form->get('security');
echo $this->formHidden($security);

$id = $form->get('id');
echo $this->formHidden($id);

$password = $form->get('password');
echo $this->formInput($password);

$submit = $form->get('submit');
echo $this->formSubmit($submit);
?>
<div class="footer">
    <p>Não tem uma conta? <a href="<?php echo $this->url('tenil-user/default', array('controller'=> 'index', 'action'=>'register')) ?>">Cadastre-se</a></p>
</div>

<?php echo $this->form()->closeTag(); ?>